YTK/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("APPYTK.urls")),
    path("", include("authentication.urls")),
    path("profiles/", include("user_profiles.urls")),
    path("announcements/", include("announcements.urls")),
    path("roles/", include("roles.urls")),
    path("kaas/", include("kaasinc.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_URL) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profiles/urls.py
from django.urls import path
from .views import profile_view, edit_profile, user_profile_list, upload_profile_picture

urlpatterns = [
    path('<str:current_name>', profile_view, name='profile'),
    path('<str:current_name>/edit', edit_profile, name='edit_profile'),
    path('<str:current_name>/pic', upload_profile_picture, name='upload_profile_picture'),
    path('', user_profile_list, name='user_profile_list'),
]

user_profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime

class User(AbstractUser):
    GENDERS = [
        ('geheim', 'Geheim'),
        ('vrouw', 'Vrouwelijk'),
        ('man', 'Mannelijk'),
        ('nb', 'Non-Binair'),
    ]

    # Profile picture
    pfp = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    
    # Name and basic info
    city = models.CharField(max_length=100)
    birthday = models.DateField(default=datetime.datetime.now())
    gender = models.CharField(max_length=10, choices=GENDERS)
    pronouns = models.CharField(max_length=15, blank=True)
    number = models.CharField(max_length=12)

    # Biography
    bio = models.TextField(max_length=1000, blank=True)

    # Trivia fields
    trivia1 = models.CharField(max_length=100, blank=True)
    trivia2 = models.CharField(max_length=100, blank=True)
    trivia3 = models.CharField(max_length=100, blank=True)
    trivia4 = models.CharField(max_length=100, blank=True)
    trivia5 = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name

    def __setitem__(self, key, value):
        setattr(self, key, value)

    def __getitem__(self, key):
        return getattr(self, key)
    

user_profiles/forms.py
from django import forms

class NewUserForm (forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter a new name'
    }))


class UserForm(forms.Form):
    GENDERS = [
        ('geheim', 'Geheim'),
        ('vrouw', 'Vrouwelijk'),
        ('man', 'Mannelijk'),
        ('nb', 'Non-Binair'),
    ]
    
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your username'
    }))

    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your name'
    }))

    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your family name'
    }))
    
    email = forms.EmailField(max_length=75, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your email'
    }))
    
    birthday = forms.DateField(widget=forms.DateInput(attrs={
        'class': 'form-control',
        'type': 'date'
    }))
    
    city = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your city'
    }))
    
    gender = forms.ChoiceField(choices=GENDERS, widget=forms.Select(attrs={
        'class': 'form-select'
    }))
    
    pronouns = forms.CharField(max_length=15, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your pronouns'
    }))
    
    number = forms.CharField(max_length=12, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your phone number'
    }))
    
    bio = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'rows': 5,
        'placeholder': 'Tell us about yourself'
    }))
    
    trivia1 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Fun fact 1'
    }))
    
    trivia2 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Fun fact 2'
    }))
    
    trivia3 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Fun fact 3'
    }))
    
    trivia4 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Fun fact 4'
    }))
    
    trivia5 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Fun fact 5'
    }))

class UploadProfilePicture(forms.Form):
    pfp = forms.FileField(widget=forms.FileInput(attrs={
        'class': 'form-control',
        'accept': 'image/*'
    }))

user_profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserForm, NewUserForm, UploadProfilePicture
from .models import User

@login_required
def profile_view(request, current_name):

    user = None
    try:
        user = User.objects.get(username__iexact=current_name)
    except User.DoesNotExist:
        return render(request, '404.html')

    return render(request, 'profile.html', {'user': user})

@login_required
def edit_profile(request, current_name):

    user = None
    try:
        user = User.objects.get(username__iexact=current_name)
    except User.DoesNotExist:
        return render(request, '404.html')

    if not request.user.has_perm("user.update") and request.user.id != user.id:
        return render(request, '404.html')

    form = None

    if request.method == 'POST':
        form = UserForm(request.POST)
        if not form.is_valid():
            return render(request, 'edit_profile.html', {'form': form})
        
        for i in form.changed_data:
            user[i] = form.cleaned_data[i]
        
        if form.is_valid():
            user.save()
            messages.success(request, "Dit profiel is succesvol bijgewerkt!")
            return redirect("profile", current_name=user.username)

    form = UserForm(initial={
        'pfp': user.pfp,
        'username': user.username,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'email': user.email,
        'birthday': user.birthday,
        'city': user.city,
        'gender': user.gender,
        'pronouns': user.pronouns,
        'number': user.number,
        'bio': user.bio,
        'trivia1': user.trivia1,
        'trivia2': user.trivia2,
        'trivia3': user.trivia3,
        'trivia4': user.trivia4,
        'trivia5': user.trivia5,
    })

    return render(request, 'edit_profile.html', {'form': form, 'profile': user})

@login_required
def user_profile_list(request):

    form = NewUserForm()
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if not form.is_valid():
            return render(request, 'list.html', {'form': form})
        
        user = User()
        user.username = form.cleaned_data['username']
        
        user.save()
        profiles = User.objects.all()
        messages.success(request, "Dit profiel is succesvol aangemaakt!")
        return render(request, 'list.html', {'profiles': profiles, 'form': form})

    profiles = User.objects.all()
    return render(request, 'list.html', {'profiles': profiles, 'form': form})

@login_required
def dashboard(request):
    profiles = User.objects.all()    
    return render(request, 'dashboard.html', {'profiles': profiles})


def upload_profile_picture(request, current_name):
    form = UploadProfilePicture()

    user = None
    try:
        user = User.objects.get(username__iexact=current_name)
    except User.DoesNotExist:
        return render(request, '404.html')

    if not request.user.has_perm("user.update") and request.user.id != user.id:
        return render(request, '404.html')

    if request.method == 'POST':
        form = UploadProfilePicture(request.POST, request.FILES)
        if not form.is_valid():
            return render(request, 'profile_pic.html', {'form': form, 'profile': user})
        user.pfp = form.cleaned_data['pfp']
        user.save()
        return redirect("profile", current_name=current_name)

    return render(request, 'profile_pic.html', {'form': form, 'profile': user})

user_profiles/templates/edit_profile.html
{% extends 'core/base.html' %}
{% load static from static %}

{% block title %}Edit Profile{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'edit_profile.css' %}">
{% endblock %}
{% block content %}
  <div id="main-content">
      <div>
        <div class="page-header">
            <a class="back-button" href="{% url 'profile' current_name=profile.username %}">
                &#8592;
            </a>
            Edit profile
        </div>
        <div id="profile-container">
          <form method="post" enctype="multipart/form-data">
            <div class="profile-row" id="row1">
              {% csrf_token %}
              <div class="rounded-card" id="profile-pfp">
                <h1><label for="{{ form.pfp.label }}">Upload uw profielfoto:</label></h1><br>
                {% if profile.pfp.url != None %}
                    <img class="square" src="{{ profile.pfp.url }}" alt="Profile pic of {{ profile.username }}">
                {% endif %}
                <a class="btn" href="{% url 'upload_profile_picture' current_name=profile.username %}">
                    Change
                </a>
              </div>
              <div class="rounded-card" id="profile-info">
                <h1>Uw Informatie</h1>
                <div id="form-labels-inputs">
                  <div class="yet-another-class" id="invisible">
                    <label for="{{ form.username.label }}">Uw username:</label><br>
                    <div class="space-filler"> </div>
                    <div class="profile-edit-inputs">
                      {{ form.username.error }}
                      {{ form.username }}<br>
                    </div>
                  </div>
                  <div class="yet-another-class">
                    <label for="{{ form.first_name.label }}">Uw voornaam:</label><br>
                    <div class="space-filler"> </div>
                    <div class="profile-edit-inputs">
                      {{ form.first_name.error }}
                      {{ form.first_name }}<br>
                    </div>
                  </div>
                  <div class="yet-another-class">
                    <label for="{{ form.last_name.label }}">Uw achternaam:</label><br>
                    <div class="space-filler"> </div>
                    <div class="profile-edit-inputs">
                      {{ form.last_name.error }}
                      {{ form.last_name }}<br>
                    </div>
                  </div>
                  <div class="yet-another-class">
                    <label for="{{ form.age.label }}">Uw geboortedag:</label><br>
                    <div class="space-filler"> </div>
                    {{ form.birthday.error }}
                    {{ form.birthday }}<br>
                  </div>
                  <div class="yet-another-class">
                    <label for="{{ form.city.label }}">Uw woonplaats:</label><br>
                    <div class="space-filler"> </div>
                    {{ form.city.error }}
                    {{ form.city }}<br>
                  </div>
                  <div class="yet-another-class">
                    <label for="{{ form.gender.label }}">Uw gender:</label><br>
                    <div class="space-filler"> </div>
                    {{ form.gender.error }}
                    {{ form.gender }}<br>
                  </div>
                  <div class="yet-another-class">
                    <label for="{{ form.pronouns.label }}">Uw voornaamwoorden:</label><br>
                    <div class="space-filler"> </div>
                    {{ form.pronouns.error }}
                    {{ form.pronouns }}<br>
                  </div>
                  <div class="yet-another-class">
                    <label for="{{ form.number.label }}">Uw telefoonnummer:</label><br>
                    <div class="space-filler"> </div>
                    {{ form.number.error }}
                    {{ form.number }}<br>
                  </div>
                  <div class="yet-another-class">
                    <label for="{{ form.email.label }}">Uw e-mailadres:</label><br>
                    <div class="space-filler"> </div>
                    {{ form.email.error }}
                    {{ form.email }}<br>
                  </div>
                </div>
              </div>
            </div>
            <div class="profile-row" id="row2">
              <div class="rounded-card" id="profile-roles">
                <h1>Uw Rollen</h1>
                <!-- Render each role as a checkbox -->
                <label for="{{ form.ceo.label }}">Chief Executive Officer (CEO)</label>
                <label for="{{ form.cco.label }}">Chief Cheese Officer (CCO)</label>
                <label for="{{ form.kaaskop.label }}">Kaaskop</label>
                <label for="{{ form.kaastester.label }}">Kaastester</label>
                <label for="{{ form.dev.label }}">Developer</label>
                <label for="{{ form.master.label }}">SCRUM Master</label>
                <label for="{{ form.owner.label }}">Product Owner</label>
                <label for="{{ form.caf.label }}">Cafetariamedewerker</label> 

              </div>
              <div class="rounded-card" id="profile-about-me">
                <h1>Biografie</h1>
                <h2><label for="{{ form.bio.label }}">Schrijf een mooie tekst over uzelf, of laat ChatGPT het doen.</label></h2><br>
                {{ form.bio }}<br>
              </div>
            </div>
            <div class="profile-row" id="row3">
              <div class="rounded-card" id="profile-trivia">
                <h1>Trivia</h1>
                <label for="{{ form.trivia1.label }}">Een leuk feitje over u.</label>
                {{ form.trivia1.error }}
                {{ form.trivia1 }}
                <br>
                <label for="{{ form.trivia2.label }}">Een leuker feitje over u.</label>
                {{ form.trivia2.error }}
                {{ form.trivia2 }}
                <br>
                <label for="{{ form.trivia3.label }}">Een nóg leuker feitje over u.</label>
                {{ form.trivia3.error }}
                {{ form.trivia3 }}
                <br/>
                <label for="{{ form.trivia4.label }}">Een haast onmogelijk leuk feitje over u.</label>
                {{ form.trivia4.error }}
                {{ form.trivia4 }}
                <br>
                <label for="{{ form.trivia5.label }}">Het allerleukste feitje over u.</label>
                {{ form.trivia5.error }}
                {{ form.trivia5 }}
                <br>
              </div>
              <div class="rounded-card" id="profile-edit-box">
                <input type="submit" value="Save Changes">
              </div>
            </div>
          </form>
        </div>
    </div>
  </div>
{% endblock %}

user_profiles/templates/list.html
{% extends 'core/base.html' %}
{% load static from static %}

{% block title %}Alle Collega's{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'profiles_list.css' %}">
{% endblock %}
{% block content %}
<!-- Main Content -->
<div id="main-content">
    <div class="all-profiles">

        <div class="page-header">
            <a class="back-button" href={% url 'home' %}>
                &#8592;
            </a>
        </div>
        
        <div class="user" id="newUser">
            <div class="initials-icon">
                <div class="initials">+</div>
            </div>
            <div class="basic-info-block">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="id_first_name">Voeg een nieuwe user toe:</label><br>
                    {{ form.username.error }}
                    {{ form.username }}<br>
                    <input type="submit" value="Opslaan">
                </form>
            </div>
        </div>

        {% for profile in profiles %}
        <a href="/profiles/{{ profile.username }}" class="user-profile-link">
            <div class="user">
                <div class="initials-icon">
                    {% if profile.pfp.url != None %}
                        <img class="initials" src="{{ profile.pfp.url }}" alt="Profile pic of {{ profile.username }}">
                    {% else %}
                        <div class="initials">{{ profile.first_name|make_list|first }}.{{ profile.last_name|make_list|first }}.</div>
                    {% endif %}
                </div>
                <div class="basic-info-block">
                    <div class="full-name">{{ profile.first_name }} {{ profile.last_name }}</div>
                    <div class="email-address">{{ profile.email }}</div>
                    <div class="phone-number">Tel.: {{ profile.number }}</div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

user_profiles/templates/profile.html
{% extends 'core/base.html' %}
{% load static from static %}
{% block title %}{{ user.username }}s Profile{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'styles.css' %}">
{% endblock %}
{% block content %}
<!-- Main Content -->
<div id="main-content">
    <div>
        <div class="page-header">
            <a class="back-button" href={% url 'user_profile_list' %}>
                &#8592;
            </a>
            Profiles
        </div>
        <div id="profile-container">
            <div class="profile-row" id="row1">
                <div class="rounded-card" id="profile-pfp">
                    {% if user.pfp.url != None %}
                        <img class="square" src="{{ user.pfp.url }}" alt="Profile pic of {{ user.username }}">
                    {% endif %}
                </div>
                <div class="rounded-card" id="profile-info">
                    <div class="info">
                        <div class="profile-info-box-q" id="profile-name">Naam</div>
                        <div class="profile-info-box" id="profile-name">{{ user.first_name }} {{user.last_name}}</div>
                    </div>
                    <div class="info">
                        <div class="profile-info-box-q" id="profile-age">Verjaardag</div>
                        <div class="profile-info-box" id="profile-age">{{ user.birthday }}</div>
                    </div>
                    <div class="info">
                        <div class="profile-info-box-q" id="profile-city">Woonplaats</div>
                        <div class="profile-info-box" id="profile-city">{{ user.city }}</div>
                    </div>
                    <div class="info">
                        <div class="profile-info-box-q" id="profile-gender">Geslacht</div>
                        <div class="profile-info-box" id="profile-gender">{{ user.gender }}</div>
                    </div>
                    <div class="info">
                        <div class="profile-info-box-q" id="profile-gender">Voornaamwoorden</div>
                        <div class="profile-info-box" id="profile-gender">{{ user.pronouns }}</div>
                    </div>
                    <div class="info">
                        <div class="profile-info-box-q" id="profile-gender">Telefoonnummer</div>
                        <div class="profile-info-box" id="profile-gender">{{ user.number }}</div>
                    </div>
                    <div class="info">
                        <div class="profile-info-box-q" id="profile-gender">Emailadres</div>
                        <div class="profile-info-box" id="profile-gender">{{ user.email }}</div>
                    </div>
                </div>
            </div>
            <div class="profile-row" id="row2">
                <div class="rounded-card" id="profile-roles">
                    <h1>Mijn Rollen</h1>
                    <div class="profile-role" id="profile-role1">CEO</div>
                    <div class="profile-role" id="profile-role2">CTO</div>
                    <div class="profile-role" id="profile-role3">CFO</div>
                </div>
                <div class="rounded-card" id="profile-about-me">
                    <h1>Alles Over Mij</h1>
                    <p>
                        {{ user.bio }}
                    </p>
                </div>
            </div>
            <div class="profile-row" id="row3">
                <div class="rounded-card" id="profile-trivia">
                    <h1>Trivia</h1>
                    <p>{{ user.trivia1 }}</p>
                    <p>{{ user.trivia2 }}</p>
                    <p>{{ user.trivia3 }}</p>
                    <p>{{ user.trivia4 }}</p>
                    <p>{{ user.trivia5 }}</p>
                    <p></p>
                </div>
                <a href="{% url 'edit_profile' current_name=user.username %}" id="profile-edit-link">
                    <div class="rounded-card" id="profile-edit-box">
                        Bewerk Dit Profiel...
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_profiles/templates/profile_pic.html
{% extends 'core/base.html' %}
{% load static from static %}
{% block title %}{{ user.username }}s Profile{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'styles.css' %}">
{% endblock %}
{% block content %}
<!-- Main Content -->
<div id="main-content">
    <div>
        <div class="page-header">
            <a class="back-button" href="{% url 'edit_profile' current_name=profile.username %}">
                &#8592;
            </a>
            Profiles
        </div>
        <div id="profile-container" style="padding-top: 0px">
            <div class="profile-row" id="row1">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="rounded-card" id="profile-pfp">
                        {{ form.pfp }}
                        {% if profile.pfp.url != None %}
                            <img class="square" src="{{ profile.pfp.url }}" alt="Profile picture of {{ user.username }}" />
                        {% endif %}
                    </div>
                    <input class="btn" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}